import {createHash} from'node:crypto';
import {execFileSync,spawnSync} from'node:child_process';
import{copyFileSync,existsSync,mkdirSync,readFileSync,readdirSync,statSync,writeFileSync}from'node:fs';
import path from'node:path';
const rows=readFileSync('/tmp/import.tsv','utf8').trim().split('\n').map(x=>{const[a,b,c,d,...e]=x.split('\t');return{sequence:+a,sourceFileId:b,url:c,createdAt:d,title:e.join('\t')}});
const exts=new Set(['.png','.jpg','.jpeg','.webp','.gif','.avif']),tmp='/tmp/adobe-import',category='红裳仙姬',personSlug='red-robed-immortal',audit=process.env.AUDIT_PATH;
mkdirSync(tmp,{recursive:true});mkdirSync(path.dirname(audit),{recursive:true});
const walk=d=>!existsSync(d)?[]:readdirSync(d,{withFileTypes:true}).flatMap(e=>{const p=path.join(d,e.name);return e.isDirectory()?walk(p):[p]});
const hash=p=>createHash('sha256').update(readFileSync(p)).digest('hex');
const uniq=a=>[...new Set(a.filter(Boolean))];
function theme(t,i){if([13,14,15,16].includes(i))return'character-sheet';if(/拼图|展示|作品集/.test(t))return'multi-panel';if(/剑|刃|战士|战姬|刺客|决斗|攻击|冲锋|勇者/.test(t))return'battle';if(/红焰|火焰|燃焰|红光/.test(t))return'fire-magic';if(/月影|夜|暗夜/.test(t))return'moon-night';if(/翡翠|翠金/.test(t))return'emerald';if(/紫/.test(t))return'violet';if(/粉/.test(t))return'pink-gold';if(/羽|光辉|圣女|白金/.test(t))return'celestial';if(/魔法|女巫|术|召唤|能量|魔力|红球|红珠|魔珠/.test(t))return'magic';return'fantasy-portrait'}
function color(t){if(/翡翠|翠金/.test(t))return'emerald-gold';if(/紫/.test(t))return'violet-gold';if(/粉/.test(t))return'pink-gold';if(/白金|羽|圣女/.test(t))return'ivory-gold';if(/蓝|星饰/.test(t))return'blue-silver';if(/黑金|黑衣|黑暗|暗夜/.test(t))return'black-gold';if(/红|朱|燃焰|火焰/.test(t))return'crimson-gold';return'golden'}
function action(t){if(/展示|作品集/.test(t))return'showcase';if(/拼图/.test(t))return'collage';if(/回眸/.test(t))return'over-shoulder-gaze';if(/凝视/.test(t))return'gaze';if(/召唤/.test(t))return'summoning';if(/飞行|浮空/.test(t))return'levitation';if(/舞/.test(t))return'dance';if(/剑|刃/.test(t))return'sword-pose';if(/攻击|冲锋|决斗/.test(t))return'combat-pose';if(/红球|红珠|魔珠|能量球/.test(t))return'crimson-orb';if(/闭眼/.test(t))return'closed-eyes';if(/托腮/.test(t))return'chin-rest';if(/执扇/.test(t))return'fan-pose';if(/力量|强大|强势/.test(t))return'power-pose';return'portrait'}
function subject(t){if(/女王/.test(t))return'queen';if(/女巫|法师|术士|魔法使/.test(t))return'sorceress';if(/战士|战姬|刺客|剑士|勇者/.test(t))return'warrior';if(/女神|圣女|仙子/.test(t))return'goddess';return'immortal-maiden'}
function outfit(t){if(/翡翠|翠金/.test(t))return['翡翠绿礼服','暗金刺绣'];if(/紫/.test(t))return['紫罗兰礼服','银金刺绣'];if(/粉/.test(t))return['粉金礼服','轻纱'];if(/白金|羽|圣女/.test(t))return['白金礼服','羽饰'];if(/蓝|星饰/.test(t))return['深蓝礼服','银色星饰'];if(/黑金|黑衣|黑暗|暗夜/.test(t))return['黑金礼服','红宝石'];if(/红|朱|燃焰|火焰/.test(t))return['红金礼服','红色轻纱'];return['东方幻想礼服','金线刺绣']}
function acts(t){const a=[];if(/回眸/.test(t))a.push('回眸凝视');if(/凝视/.test(t))a.push('直视镜头');if(/召唤/.test(t))a.push('魔法召唤');if(/飞行|浮空/.test(t))a.push('浮空');if(/舞/.test(t))a.push('舞蹈');if(/剑|刃/.test(t))a.push('持剑');if(/攻击|冲锋|决斗/.test(t))a.push('战斗动作');if(/红球|红珠|魔珠|能量球/.test(t))a.push('托举能量球');if(/闭眼/.test(t))a.push('闭眼');if(/托腮/.test(t))a.push('托腮');if(/执扇/.test(t))a.push('执扇');return a.length?a:['静态姿态']}
function pngSize(b){const s=Buffer.from([137,80,78,71,13,10,26,10]);if(b.length<24||!b.subarray(0,8).equals(s))throw Error('文件不是有效 PNG');const width=b.readUInt32BE(16),height=b.readUInt32BE(20);if(width<64||height<64)throw Error(`无效尺寸 ${width}x${height}`);return{width,height}}
const oldFiles=walk('images').filter(p=>exts.has(path.extname(p).toLowerCase())),oldHashes=new Map;for(const p of oldFiles)try{oldHashes.set(hash(p),p.split(path.sep).join('/'))}catch{}
let before=oldFiles.length;try{before=+JSON.parse(readFileSync('data/gallery.json','utf8')).count||before}catch{}
const seen=new Map,multi=new Set([13,14,15,16,105,106,108]),featured=new Set([1,6,13,15,18,26,28,37,47,56,66,75,85,95,105,109,118,122,128,134,137]);
const report={generatedAt:new Date().toISOString(),bridge:'Adobe asset_openai_file_upload',discoveredGeneratedImages:rows.length,validOriginalImages:0,effectiveUniqueOriginalImages:0,successAdded:0,repositoryExistingSkipped:0,duplicateSkipped:0,failed:0,galleryCountBefore:before,galleryCountAfter:null,personCategory:category,personSlug,themes:[],addedPaths:[],repositoryExisting:[],duplicates:[],failures:[],records:[]};
for(const item of rows){item.theme=theme(item.title,item.sequence);item.layout=multi.has(item.sequence)?'多格拼图':'独立大图';item.lens=item.sequence>=95?'人物特写':'半身或全身';item.slug=`${color(item.title)}-${action(item.title)}-${subject(item.title)}-${String(item.sequence).padStart(3,'0')}`;const rec={sequence:item.sequence,sourceFileId:item.sourceFileId,originalFileName:'imagegen.png',format:'png',generationRound:item.createdAt,title:item.title,theme:item.theme,layout:item.layout};const temp=path.join(tmp,`${String(item.sequence).padStart(3,'0')}.png`);
try{const r=spawnSync('curl',['-L','--fail','--silent','--show-error','--retry','3','--retry-delay','2','--retry-all-errors',item.url,'-o',temp],{encoding:'utf8'});if(r.status!==0)throw Error(`curl 下载失败（${r.status}）：${r.stderr||''}`.trim());const st=statSync(temp);if(st.size<10000)throw Error(`文件过小：${st.size} bytes`);const mime=execFileSync('file',['-b','--mime-type',temp],{encoding:'utf8'}).trim();if(mime!=='image/png')throw Error(`扩展名与 MIME 不一致：.png / ${mime}`);const b=readFileSync(temp),{width,height}=pngSize(b),h=hash(temp);report.validOriginalImages++;if(seen.has(h)){report.duplicateSkipped++;report.duplicates.push({sequence:item.sequence,duplicateOfSequence:seen.get(h),sha256:h,reason:'当前会话内完全相同的图片内容'});report.records.push({...rec,width,height,mime,sha256:h,status:'duplicate'});continue}seen.set(h,item.sequence);if(oldHashes.has(h)){report.repositoryExistingSkipped++;report.repositoryExisting.push({sequence:item.sequence,path:oldHashes.get(h),sha256:h});report.records.push({...rec,width,height,mime,sha256:h,status:'repository-existing',path:oldHashes.get(h)});continue}
const dir=path.posix.join('images',personSlug,item.theme);mkdirSync(dir,{recursive:true});let target=path.posix.join(dir,`${item.slug}.png`);if(existsSync(target))target=path.posix.join(dir,`${item.slug}-${h.slice(0,8)}.png`);copyFileSync(temp,target);const side=target.replace(/\.png$/i,'.json'),lens=item.layout==='多格拼图'?['多格拼图','角色设定展示']:item.lens==='人物特写'?['人物特写','胸像','独立大图']:['半身','全身构图','独立大图'],interaction=/闭眼/.test(item.title)?['闭眼','侧面']:['直视镜头','互动视线'],emotion=/战|剑|攻击|决绝|强大|威严/.test(item.title)?['神秘','清冷','凌厉']:['神秘','清冷','温柔','妩媚'],tags=uniq([item.theme,category,'成年东方女性','黑色高盘发','琥珀金眼','金色发饰','红宝石耳坠','红裳仙姬系列',...outfit(item.title),...lens,...acts(item.title),...interaction,...emotion]);
const meta={title:item.title,description:`${category}「${item.title}」原始生成作品。画面保持同一人物身份，以黑色高盘发、琥珀金眼、金红珠宝与东方幻想服饰为核心特征，采用${item.layout}构图，呈现${item.theme}主题、细腻材质和人物互动视线。`,category,tags,createdAt:item.createdAt,featured:featured.has(item.sequence),width,height,sourceFileId:item.sourceFileId,sourceBridge:'Adobe asset_openai_file_upload',sourceSha256:h,composition:item.layout,generationSequence:item.sequence};writeFileSync(side,JSON.stringify(meta,null,2)+'\n');oldHashes.set(h,target);report.successAdded++;report.addedPaths.push(target);report.records.push({...rec,width,height,mime,sha256:h,status:'added',path:target,metadataPath:side})}
catch(e){report.failed++;report.failures.push({sequence:item.sequence,sourceFileId:item.sourceFileId,generationRound:item.createdAt,reason:e.message});report.records.push({...rec,status:'failed',reason:e.message});console.error(`图片 ${item.sequence} 导入失败：${e.message}`)}}
report.effectiveUniqueOriginalImages=rows.length-report.duplicateSkipped;report.themes=uniq(report.records.map(r=>r.theme)).sort();const actual=report.successAdded+report.repositoryExistingSkipped+report.failed;report.reconciliation={expected:report.effectiveUniqueOriginalImages,actual,matches:actual===report.effectiveUniqueOriginalImages};if(!report.reconciliation.matches)throw Error(`数量核对失败：expected=${report.reconciliation.expected}, actual=${actual}`);writeFileSync(audit,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({discovered:report.discoveredGeneratedImages,valid:report.validOriginalImages,unique:report.effectiveUniqueOriginalImages,added:report.successAdded,existing:report.repositoryExistingSkipped,duplicates:report.duplicateSkipped,failed:report.failed},null,2));
